spring:
  application:
    name: sgpa
  datasource:
    url: ${SPRING_URL_DB}
    username: ${SPRING_DBUSER}
    password: ${SPRING_PASSWORD_DB}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
  mail:
    host: mailpit.localhost
    port: 1025
    username:
    password:
    protocol: smtp
