spring:
  application:
    name: sgpa
  datasource:
    url: ${SPRING_URL_DB}
    username: ${SPRING_DBUSER}
    password: ${SPRING_PASSWORD_DB}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
  mail:
    host: mailpit.matheushenrique.dev.br
    port: 1025
    username:
    password:
    protocol: smtp

logging:
  file:
    name: logs/sgpa-logs.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 10
aws:
sgpa:
  storage:
    provider: ${STORAGE_PROVIDER} # 'AZURE' ou 'S3'
  upload:
    service: ${STORAGE_SERVICE} # AWS, R2, MinIO, Supabase, Blob.
    config:
      s3:
        endpoint: ${STORAGE_ENDPOINT}
        accesskey: ${STORAGE_ACCESSKEY}
        secretkey: ${STORAGE_SECRETKEY}
        region:
          name: ${STORAGE_REGION}
        bucket:
          name: ${STORAGE_BUCKET}
      azure:
        connectio-string: ${STORAGE_STRING}
        container-name: ${STORAGE_CONTAINER}