spring:
  application:
    name: sgpa
  datasource:
    url: ${SPRING_URL_DB}
    username: ${SPRING_DBUSER}
    password: ${SPRING_PASSWORD_DB}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
  mail:
    host: mailpit.matheushenrique.dev.br
    port: 1025
    username:
    password:
    protocol: smtp

logging:
  file:
    name: logs/sgpa-logs.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 10
aws:
sgpa:
  storage:
    provider: AZURE # 'AZURE' ou 'S3'
  upload:
    service: S3 # AWS, R2, MinIO, Supabase, Blob.
    config:
      s3:
        endpoint:
        accesskey:
        secretkey:
        region:
          name:
        bucket:
          name:
      azure:
        connectio-string:
        container-name: