package dev.matheushenrique.sgpa.enums;

import lombok.Data;


public enum PermissionEnum {

    CRIAR_PERFIL("ROLE_CRIAR_PERFIL"),
    EDITAR_PERFIL("ROLE_EDITAR_PERFIL"),
    ATRIBUIR_PERFIL("ROLE_ATRIBUIR_PERFIL"),
    DELETAR_PERFIL("ROLE_DELETAR_PERFIL"),

    CRIAR_PROCESSO("ROLE_CRIAR_PROCESSO"),
    EDITAR_PROCESSO("ROLE_EDITAR_PROCESSO"),
    VISUALIZAR_PROCESSO("ROLE_VISUALIZAR_PROCESSO"),
    DELETAR_PROCESSO("ROLE_DELETAR_PROCESSO"),

    CRIAR_DEPARTAMENTO("ROLE_CRIAR_DEPARTAMENTO"),
    EDITAR_DEPARTAMENTO("ROLE_EDITAR_DEPARTAMENTO"),
    ATRIBUIR_DEPARTAMENTO("ROLE_ATRIBUIR_DEPARTAMENTO"),
    DELETAR_DEPARTAMENTO("ROLE_DELETAR_DEPARTAMENTO"),

    CRIAR_SETOR("ROLE_CRIAR_SETOR"),
    EDITAR_SETOR("ROLE_EDITAR_SETOR"),
    DELETAR_SETOR("ROLE_DELETAR_SETOR"),
    VISUALIZAR_SETOR("ROLE_VISUALIZAR_SETOR"),


    CRIAR_SERVICO("ROLE_CRIAR_SERVICO"),
    EDITAR_SERVICO("ROLE_EDITAR_SERVICO"),
    DELETAR_SERVICO("ROLE_DELETAR_SERVICO"),
    VISUALIZAR_SERVICO("ROLE_VISUALIZAR_SERVICO");


    private final String permission;

    PermissionEnum(String permission) {
        this.permission = permission;
    }
    public String getPermission() {
        return permission;
    }
}
